Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.define "ceddibaoS" do |master|
    master.vm.hostname = "ceddibaoS"
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.provider "virtualbox" do |vb|
      vb.name = "ceddibaoS"
      vb.memory = "1024"
      vb.cpus = 1
    end
    master.vm.provision "shell", path: "scripts/master_startup.sh"
  end

  config.vm.define "ceddibaoSW" do |worker|
    worker.vm.hostname = "ceddibaoSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "ceddibaoSW"
      vb.memory = "1024"
      vb.cpus = 1
    end
    worker.vm.provision "shell", path: "scripts/worker_startup.sh"
  end
end
